# code-server-configmaps.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: code-server-configs
  # 命名空間確定後，以下所列的元件都需部署在相同的命名空間中
  # Deployment、ConfigMap、Secret、Service 與 Ingress
  namespace: devtools
data:
  # 設定 code-server 使用延伸模組的位址
  # 會需要設定這個的原因是因為 Microsoft Store 只支援其自家產品
  # 第三方產品只能使用第三方的延伸模組來源
  codeServer.extensionsGallery: |-
    {
      "serviceUrl": "https://open-vsx.org/vscode/gallery",
      "itemUrl": "https://open-vsx.org/vscode/item"
    }
